import TanstackProvider from "@/src/shared/providers/TanstackProvider";
import { UserProvider } from "@/src/shared/contexts/UserContext";

import { Nunito, Inter, Roboto } from "next/font/google";
import type { Metadata } from "next";
import { Toaster } from "sonner";

import "./globals.css";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${inter.variable} ${roboto.variable} font-sans antialiased`}
      >
        <TanstackProvider>
          <UserProvider>{children}</UserProvider>
          <Toaster position="top-right" richColors />
        </TanstackProvider>
      </body>
    </html>
  );
}
